// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUxQheqvhCnptbWSvZBg8bz2ihlQCe9Jg',
    appId: '1:804067921325:web:07c1036dde200a97eae524',
    messagingSenderId: '804067921325',
    projectId: 'glamora-6f028',
    authDomain: 'glamora-6f028.firebaseapp.com',
    storageBucket: 'glamora-6f028.firebasestorage.app',
    measurementId: 'G-8L702XSXN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBinjTbLMCFvqYyYRA7G-oNoNpHanpnII',
    appId: '1:804067921325:android:114911c571ff8dcceae524',
    messagingSenderId: '804067921325',
    projectId: 'glamora-6f028',
    storageBucket: 'glamora-6f028.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaow0pBIVWNigmngdycWab8kXH1nR9Cik',
    appId: '1:804067921325:ios:fe687d8d7854db34eae524',
    messagingSenderId: '804067921325',
    projectId: 'glamora-6f028',
    storageBucket: 'glamora-6f028.firebasestorage.app',
    iosBundleId: 'com.example.glamora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaow0pBIVWNigmngdycWab8kXH1nR9Cik',
    appId: '1:804067921325:ios:fe687d8d7854db34eae524',
    messagingSenderId: '804067921325',
    projectId: 'glamora-6f028',
    storageBucket: 'glamora-6f028.firebasestorage.app',
    iosBundleId: 'com.example.glamora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUxQheqvhCnptbWSvZBg8bz2ihlQCe9Jg',
    appId: '1:804067921325:web:651dca86e4088ab2eae524',
    messagingSenderId: '804067921325',
    projectId: 'glamora-6f028',
    authDomain: 'glamora-6f028.firebaseapp.com',
    storageBucket: 'glamora-6f028.firebasestorage.app',
    measurementId: 'G-ECNE1X91W3',
  );
}
